# Generated by Django 4.0.3 on 2022-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'nickname'], 'verbose_name': 'Зарегистрированные пользователи', 'verbose_name_plural': 'Зарегистрированные пользователи'},
        ),
        migrations.AlterField(
            model_name='women',
            name='mail',
            field=models.CharField(max_length=22, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='women',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='women',
            name='password',
            field=models.CharField(max_length=32, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации'),
        ),
    ]
